language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t beingjd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true beingjd/react-test npm test

after_success:
  - docker build -t beingjd/docker-client ./client
  - docker build -t beingjd/docker-nginx ./nginx
  - docker build -t beingjd/docker-server ./server
  - docker build -t beingjd/docker-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the dockerhub
  - docker push beingjd/docker-client
  - docker push beingjd/docker-nginx
  - docker push beingjd/docker-server
  - docker push beingjd/docker-worker
