sudo: required
services:
  - docker

before_install:
  - docker build -t jd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jd/react-test npm test -- --coverage

after_success:
  - docker build -t jd/docker-client ./client
  - docker build -t jd/docker-nginx ./nginx
  - docker build -t jd/docker-server ./server
  - docker build -t jd/docker-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the dockerhub
  - docker push jd/docker-client
  - docker push jd/docker-nginx
  - docker push jd/docker-server
  - docker push jd/docker-worker
