language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t desaijay315/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true desaijay315/react-test npm test

after_success:
  - docker build -t desaijay315/docker-client ./client
  - docker build -t desaijay315/docker-nginx ./nginx
  - docker build -t desaijay315/docker-server ./server
  - docker build -t desaijay315/docker-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the http://hub.docker.com
  - docker push desaijay315/docker-client
  - docker push desaijay315/docker-nginx
  - docker push desaijay315/docker-server
  - docker push desaijay315/docker-worker

# deploy:
#   provider: elasticbeanstalk
#   region: ap-south-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-ap-south-1-583044482327
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
